### ISSUE TITLE
I can't see deleted messages

### ISSUE THREAD

**Issue by Blonkyblonk** [Schwartzblat/WhatsApp-Web-Plus#13]
i got error 
"Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'processRenderableMessages')"

**Comment by Schwartzblat** [comment]
Please update the extension, reload it and try again. I have already fixed it.

**Comment by Blonkyblonk** [comment]
I have updated to the latest version, but I still can't see view once message

**Comment by Schwartzblat** [comment]
1. It's not the subject of the issue, you can open another one if you had a problem with one of the features.
2. I am working on that right now so it will be working again within a hour :)
